---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bitwarden.events" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "bitwarden.events" . }}
    app.kubernetes.io/component: events
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.component.events.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{- if .Values.general.nodeSelector }}
  nodeSelector:
    {{- toYaml .Values.general.nodeSelector | indent 8 }}
  {{- end }}
  {{- if .Values.general.tolerations }}
  tolerations:
    {{- toYaml .Values.general.tolerations | indent 8 }}
  {{- end }}
  replicas: 1
  strategy:
    type: "{{ .Values.component.events.deploymentStrategy }}"
  selector:
    matchLabels:
      app: {{ template "bitwarden.events" . }}
  template:
    metadata:
      labels:
        app: {{ template "bitwarden.events" . }}
        app.kubernetes.io/component: events
{{ include "bitwarden.labels" . | indent 8 }}
    spec:
    {{- if .Values.component.events.podServiceAccount }}
      serviceAccount: "{{ .Values.component.events.podServiceAccount }}"
      serviceAccountName: "{{ .Values.component.events.podServiceAccount }}"
    {{- end }}
    {{- if and .Values.volume.logs .Values.volume.logs.enabled }}
      initContainers:
      - name: create-mount-subdir
        command:
          - "/bin/bash"
          - "-c"
        args: ['
          mkdir -p /logs/events
        ']
        image: "bitnami/kubectl:1.26.11"
        volumeMounts:
          - name: applogs
            mountPath: /logs
    {{- end }}
      containers:
      - name: {{ template "bitwarden.events" . }}
        image: "{{ .Values.component.events.image.name }}:{{ default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride }}"
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-config-map
          - secretRef:
              name: "{{ .Values.secrets.secretName }}"
          - secretRef:
              name: {{ template "bitwarden.keyssecret" . }}
          {{- if .Values.database.enabled }}
          - secretRef:
              name: {{ .Release.Name }}-sql-connection-string
          {{- end }}
        env:
          - name: ASPNETCORE_URLS
            value: http://+:5000
        livenessProbe:
          httpGet:
            path: /alive
            port: 5000
          initialDelaySeconds: 180
        ports:
        - containerPort: 5000
        resources:
{{ toYaml .Values.component.events.resources | indent 10 }}
        volumeMounts:
        {{- if .Values.secrets.secretProviderClass}}
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        {{- end }}
        {{- if and .Values.volume.logs .Values.volume.logs.enabled }}
        - name: applogs
          mountPath: /etc/bitwarden/logs
          subPath: events
        {{- end }}
        securityContext:
{{ toYaml .Values.component.events.securityContext | indent 10 }}
      volumes:
        {{- if .Values.secrets.secretProviderClass}}
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.secrets.secretProviderClass }}
        {{- end }}
        {{- if and .Values.volume.logs .Values.volume.logs.enabled }}
        - name: applogs
          persistentVolumeClaim:
            claimName: {{ template "bitwarden.applogs" . }}
        {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bitwarden.events" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: events
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.component.events.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  selector:
    app: {{ template "bitwarden.events" . }}
  ports:
  - port: 5000
    targetPort: 5000
